vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile_image:
            uri_prefix: /patients_records/profile_images
            upload_destination: '%kernel.project_dir%/patients_records/profile_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        test_requisition:
            uri_prefix: /patients_records/ test_requisition
            upload_destination: '%kernel.project_dir%/patients_records/test_requisition'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true



